modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/PickUpTNT/issues"
license = "All Right Reserved"

[[mods]]
modId = "pick_up_tnt"
version = "1.1"
displayName = "PickUpTNT"
authors = "IAFEnvoy"
description = '''
Make TNT pickable and more fun.
'''
logoFile = "logo.jpg"

[[dependencies.pick_up_tnt]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pick_up_tnt]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,1.22)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "pick_up_tnt.mixins.json"